package com.beautyandthelua.lexer;

public enum TokenType {
    AND, BREAK, CONTINUE, DO, ELSE, ELSEIF, END,
    FALSE, FOR, FUNCTION, GOTO, IF, IN, LOCAL,
    NIL, NOT, OR, REPEAT, RETURN, THEN, TRUE,
    UNTIL, WHILE,
    TYPE, EXPORT, IMPORT, TYPEOF,
    IDENTIFIER, NUMBER, STRING,
    COMMENT, SHEBANG,
    LPAREN, RPAREN, LCURLY, RCURLY, LBRACK, RBRACK,
    COMMA, SEMI, COLON, DOT,
    VARARG, CONCAT,
    LABEL,
    PLUS, MINUS, STAR, SLASH, PERCENT, CARET, HASH,
    IDIV, AMPERSAND, PIPE, TILDE, SHL, SHR,
    EQ, NE, LE, GE, LT, GT, ASSIGN,
    PLUS_EQ, MINUS_EQ, STAR_EQ, SLASH_EQ, IDIV_EQ, PERCENT_EQ, CARET_EQ, CONCAT_EQ,
    ARROW, QMARK, ATRATE,
    NEWLINE, EOF, ILLEGAL // yea ur illegal >:(
}
